apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80          #This is the port on which the service is exposed within the cluster.
      targetPort: 80        # This is the port on which the application inside the pod is listening.
      nodePort: 30007   # This is the port on each node that routes traffic to the service
