apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-download-cronjob
spec:
  schedule: "0 * * * *"  # Runs every hour at the start of the hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: s3-downloader
            image: amazon/aws-cli:latest
            command: ["sh", "-c"]
            args:
              - aws s3 sync s3://s3bucket-temp-kodecraft/test_folder/ /hostpath/data --region ap-southeast-1;
                echo "Download complete"
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
            volumeMounts:
            - name: hostpath
              mountPath: /hostpath/data
          restartPolicy: OnFailure
          volumes:
          - name: hostpath
            hostPath:
              path: /hostpath/data
              type: Directory
