apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVVGM9FQVFZMlA=  # Encoded  Access key
  AWS_SECRET_ACCESS_KEY: VzB6cjB6U3NOUFpIN1hCME8yemN1bTBKS0FPd==  # Encoded Secret Key
