apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-no-volumes
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: helper-container
      image: ubuntu:latest
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Helper container running: $(date)";
            sleep 10;
          done
