apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
spec:
  dnsPolicy: "None"  # Use custom DNS settings
  dnsConfig:
    nameservers:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4  # Google DNS
  containers:
    - name: webapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

    - name: fetcher-container
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          mkdir -p /shared-data
          while true; do
            echo "Fetching webpage..."
            wget -O /shared-data/index.html https://raw.githubusercontent.com/mdn/beginner-html-site/gh-pages/index.html || echo "Failed to fetch"
            echo "Listing contents of /shared-data:"
            ls -l /shared-data
            sleep 3600
          done
      volumeMounts:
        - name: shared-data
          mountPath: /shared-data

  volumes:
    - name: shared-data
      emptyDir: {}

