apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
spec:
  containers:
    - name: webapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

    - name: fetcher-container
      image: busybox:latest
      args:
        - /bin/sh
        - -c
        - |
          while true; do
            wget -O /shared-data/index.html https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
            ls -l /shared-data
            sleep 3600
          done
      volumeMounts:
        - name: shared-data
          mountPath: /shared-data

  volumes:
    - name: shared-data
      emptyDir: {}
