apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-no-volumes
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "echo Hello from BusyBox && sleep 3600"]
