apiVersion: v1
kind: Pod
metadata:
  name: app-secret-demo-volume
  labels:
    name: simple-pod-green
spec:
  containers:
  - name: simple-app-con
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: app-secret-volume
      mountPath: /etc/secret
  volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret
