apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-demo
  labels:
    name: simple-pod-green
spec:
  containers:
  - name: simple-app-con
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:                 # Corrected reference to 'secretRef'
        name: app-secret
