apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple-pod-green
spec:
  containers:
  - name: simple-app-con
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: app-config
