
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-persistent-storage1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-persistent-storage1
        persistentVolumeClaim:
          claimName: pvc-claim-1 

