apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvolume1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-03158fd8fb9bce40b 
    fsType: ext4
